# Generated by Django 3.2.7 on 2022-08-17 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20220817_0941'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infor',
            old_name='student',
            new_name='student_id',
        ),
    ]
