# Generated by Django 3.2.7 on 2022-08-17 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_rename_student_infor_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='infor',
            name='objections',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
